<center style="font-size: 26px"> <b>Проверка уровня знаний Python</b></center>

### Проверка построена следующим образом:

- К каждому блоку приложены практические задания по теме блока
- К каждому практическому заданию приложен либо рабочий файл, либо дано вводное условие
- Для успешного прохождения проверки требуется правильно ответить на 10/15 вопросов
- Корректным ответом на вопрос считается любой работоспособный код, позволяющий достичь корректного результата (и использующий проверяемый синтаксис, если это указано в условии задания)

<center style="background-color: #23B04A; color: white; font-size: 16px"><b>NumPy</b></center>

`Numpy` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.

### Технический код:
Данная часть нужна исключительно для корректной работы данной тетради. Исполните блок (Shift + Enter), не вдаваясь в суть написанного.

In [1]:
# обеспечиваем совместимость с Python 2 и 3
from __future__ import (absolute_import, division, print_function, unicode_literals)

# отключаем предупреждения дистрибутива Anaconda
import warnings
warnings.simplefilter('ignore')

### Практические задания:

In [2]:
# Импортируем библиотеки NumPy и Pandas
import numpy as np
import pandas as pd

#### 1. Создание массивов
Создайте и перемножьте одномерный и двумерный массивы при помощи библиотеки NumPy

In [5]:
a = np.array([1,2])
b = np.array([[1,2],
              [3,4]])
a * b

array([[1, 4],
       [3, 8]])

#### 2. Методы создания массивов
Создайте один и тот же массив 3-мя разными способами при помощи библиотеки NumPy

In [13]:
a = np.array([1,2,3])
b = np.concatenate(([1,2],[3]))
c = np.arange(1,4,1)
a,b,c

(array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3]))

#### 3. Индексирование массивов

Напишите код, производящий указанные в комментариях операции с массивами

In [65]:
a = np.diag(np.arange(3))  # Выделите значение = 1
a_out = np.where(a==1)[0]     # Я поняла задание так, что надо найти и вывести элемент массива, равный единице
print(a_out)                  # Но по остальным подпунктам, кажется, нужно было просто вывести первый элемент a[0][0]


b = np.random.rand(5, 5)  # Выделите первую строку
print(b[0])

c = np.arange(10) # Присвойте значение = 25 элементам массива с 3 по 6 включительно
c[2:5] = 25
print(c)

[1]
[0.89557033 0.34068848 0.0646732  0.86411967 0.29087245]
[ 0  1 25 25 25  5  6  7  8  9]


#### 4. Индексирование масками

Выберите из предоставленного массива значения, делящиеся на 3 без остатка, и присвойте им значение = 10  

In [66]:
np.random.seed(3)
a = np.random.random_integers(0, 20, 15)
b = a%3==0
a[b]=10


#### 5. Меры центральной тенденции и меры вариации

Напишите код, находящий указанные в комментариях значения

In [59]:
a = np.linspace(0, 20, 5)  # Найти среднее арифметическое массива
np.mean(a)


b = np.linspace(0, 30, 10)  # Найти медианное значение массива
np.median(b)


c = np.linspace(0, 10, 10)  # Найти кумулятивную сумму элементов массива
np.cumsum(c)


[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[ 0.          1.11111111  3.33333333  6.66666667 11.11111111 16.66666667
 23.33333333 31.11111111 40.         50.        ]


<center style="background-color: #23B04A; color: white; font-size: 16px"><b>Pandas</b></center>

`Pandas` - это библиотека Python, предоставляющая широкие возможности для анализа данных. С ее помощью очень удобно загружать, обрабатывать и анализировать табличные данные с помощью SQL-подобных запросов. В связке с библиотеками Matplotlib и Seaborn появляется возможность удобного визуального анализа табличных данных (данные библиотеки включены в следующий уровень assessment'а).

#### 6. Чтение и первичная информация о файле
Выведите первые 15 значений (строк) датафрейма, полученного из файла 'adult.data' 

In [116]:
# читаем файл и загоняем в датафрейм
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', header=None)
df.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 
'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'salary']


In [78]:
df[:15]

age          workclass  fnlwgt      education  education-num  \
0    39          State-gov   77516      Bachelors             13   
1    50   Self-emp-not-inc   83311      Bachelors             13   
2    38            Private  215646        HS-grad              9   
3    53            Private  234721           11th              7   
4    28            Private  338409      Bachelors             13   
5    37            Private  284582        Masters             14   
6    49            Private  160187            9th              5   
7    52   Self-emp-not-inc  209642        HS-grad              9   
8    31            Private   45781        Masters             14   
9    42            Private  159449      Bachelors             13   
10   37            Private  280464   Some-college             10   
11   30          State-gov  141297      Bachelors             13   
12   23            Private  122272      Bachelors             13   
13   32            Private  205019     Assoc-acdm             12   
14   40            Private  121772      Assoc-voc             11   

            marital-status          occupation    relationship  \
0            Never-married        Adm-clerical   Not-in-family   
1       Married-civ-spouse     Exec-managerial         Husband   
2                 Divorced   Handlers-cleaners   Not-in-family   
3       Married-civ-spouse   Handlers-cleaners         Husband   
4       Married-civ-spouse      Prof-specialty            Wife   
5       Married-civ-spouse     Exec-managerial            Wife   
6    Married-spouse-absent       Other-service   Not-in-family   
7       Married-civ-spouse     Exec-managerial         Husband   
8            Never-married      Prof-specialty   Not-in-family   
9       Married-civ-spouse     Exec-managerial         Husband   
10      Married-civ-spouse     Exec-managerial         Husband   
11      Married-civ-spouse      Prof-specialty         Husband   
12           Never-married        Adm-clerical       Own-child   
13           Never-married               Sales   Not-in-family   
14      Married-civ-spouse        Craft-repair         Husband   

                   race      sex  capital-gain  capital-loss  hours-per-week  \
0                 White     Male          2174             0              40   
1                 White     Male             0             0              13   
2                 White     Male             0             0              40   
3                 Black     Male             0             0              40   
4                 Black   Female             0             0              40   
5                 White   Female             0             0              40   
6                 Black   Female             0             0              16   
7                 White     Male             0             0              45   
8                 White   Female         14084             0              50   
9                 White     Male          5178             0              40   
10                Black     Male             0             0              80   
11   Asian-Pac-Islander     Male             0             0              40   
12                White   Female             0             0              30   
13                Black     Male             0             0              50   
14   Asian-Pac-Islander     Male             0             0              40   

    native-country  salary  
0    United-States   <=50K  
1    United-States   <=50K  
2    United-States   <=50K  
3    United-States   <=50K  
4             Cuba   <=50K  
5    United-States   <=50K  
6          Jamaica   <=50K  
7    United-States    >50K  
8    United-States    >50K  
9    United-States    >50K  
10   United-States    >50K  
11           India    >50K  
12   United-States   <=50K  
13   United-States   <=50K  
14               ?    >50K

Каждая строка данного фрейма - это участник социологического опроса, проведённого в Америке 

#### 7. Индексация с условием
Вынесите в новый датафрейм с названием df_work мужчин (признак *sex*) старше 35 (признак *age*)  

In [119]:
df_work = df[(df['sex'] == ' Male') & (df['age'] > 35)]
df_work



age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
7       52   Self-emp-not-inc  209642        HS-grad              9   
...    ...                ...     ...            ...            ...   
32548   65   Self-emp-not-inc   99359    Prof-school             15   
32550   43   Self-emp-not-inc   27242   Some-college             10   
32552   43            Private   84661      Assoc-voc             11   
32554   53            Private  321865        Masters             14   
32557   40            Private  154374        HS-grad              9   

            marital-status          occupation    relationship    race    sex  \
0            Never-married        Adm-clerical   Not-in-family   White   Male   
1       Married-civ-spouse     Exec-managerial         Husband   White   Male   
2                 Divorced   Handlers-cleaners   Not-in-family   White   Male   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   Male   
7       Married-civ-spouse     Exec-managerial         Husband   White   Male   
...                    ...                 ...             ...     ...    ...   
32548        Never-married      Prof-specialty   Not-in-family   White   Male   
32550   Married-civ-spouse        Craft-repair         Husband   White   Male   
32552   Married-civ-spouse               Sales         Husband   White   Male   
32554   Married-civ-spouse     Exec-managerial         Husband   White   Male   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   Male   

       capital-gain  capital-loss  hours-per-week  native-country  salary  
0              2174             0              40   United-States   <=50K  
1                 0             0              13   United-States   <=50K  
2                 0             0              40   United-States   <=50K  
3                 0             0              40   United-States   <=50K  
7                 0             0              45   United-States    >50K  
...             ...           ...             ...             ...     ...  
32548          1086             0              60   United-States   <=50K  
32550             0             0              50   United-States   <=50K  
32552             0             0              45   United-States   <=50K  
32554             0             0              40   United-States    >50K  
32557             0             0              40   United-States    >50K  

[12419 rows x 15 columns]

#### 8. Группировка и меры центральной тенденции 
Сгруппируйте всех опрошенных по уровню образования (признак *education*) и найдите среднее значение по каждому из числовых (type = int) столбцов в каждой из получившихся групп

In [ ]:
# ВАШ КОД ЗДЕСЬ

#### 9. Объединения и слияния
Объедините имеющийся датафрейм adult.data с прописанными ниже df_2 (новая колонка) и df_3 (новая строка), затем отсортируйте по признаку *age*

In [ ]:
df_2 = pd.DataFrame({'random_column': np.random.rand(32561)})
df_3 = pd.DataFrame({'age': 40, 'workclass': 'Self-emp-not-inc', 'fnlwgt': 135415, 'education': 'Some-college', 'education-num': 10, 'marital-status': 'Married-civ-spouse', 'occupation': 'Other-service', 'relationship': 'Wife', 'race': 'White', 'sex': 'Female', 'capital-gain': 0, 'capital-loss': 0, 'hours-per-week': 5, 'native-country': 'United-States', 'salary': '<=50K'}, index=[32562])

# ВАШ КОД ЗДЕСЬ

#### 10. Применение функций 
Замените каждое значение в каждом из числовых (type == int) столбцов на среднеквадратичное отклонение по этому столбцу

In [ ]:
# ВАШ КОД ЗДЕСЬ

<center style="background-color: #23B04A; color: white; font-size: 16px"><b>Анализ данных по доходу населения UCI Adult</b></center>

### Практические задания:

#### Обновляем файл adult.data и решаем задания ниже на нём

Уникальные значения признаков в датафрейме:
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

#### 11. Каков средний возраст (признак *age*) мужчин?

In [ ]:
# ВАШ КОД ЗДЕСЬ

**12. Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год? **

In [ ]:
# ВАШ КОД ЗДЕСЬ

**13. Найдите таким образом максимальный возраст мужчин расы *Amer-Indian-Eskimo*.**

In [ ]:
# ВАШ КОД ЗДЕСЬ

**14. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много (*salary* >50k)?**

In [ ]:
# ВАШ КОД ЗДЕСЬ

**15. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [ ]:
# ВАШ КОД ЗДЕСЬ